### ISSUE TITLE
Add "Output Enable" gpio for FTDI Gpio driver

### ISSUE THREAD

**Issue by superna9999** [linux-msm/cdba#43]
Since the FTDI is hot-pluggable, the output lines can be protected for unwanted changes by a supplementary GPIO that allows the FTDI gpio output to be enabled.

**Comment by lumag** [comment]
Is this a real usecase for that, or pure observation?

**Comment by superna9999** [comment]
It is for the new debug boards, we have a hack off-tree to handle this already but it's time to make it formal

**Comment by lumag** [comment]
ack
