### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by lumag** [linux-msm/cdba#47]
I think it might be nice to mark the 1.0 release at some point.
Let's define the features that we need there before we can cut a release:

- [x] #44 
- [x] #43
       #45 
- [x] #37 
- [x] #48
      #49

**Comment by lumag** [comment]
cc @konradybcio @superna9999 @calebccff

**Comment by calebccff** [comment]
imho client only builds isn't a blocker for a 1.0. and neither is the ftdi gpio

anyone trying to set up the server is realistically going to need to build from source... only the client benefits from having cdba be packaged. could be tag a 0.9.0 with the alpine me merged?

**Comment by superna9999** [comment]
It would be easy with meson to add this feature and ignore the dependencies

**Comment by lumag** [comment]
@konradybcio all items are closed. Time to act!

**Comment by konradybcio** [comment]
@lumag in good faith that we didn't need a pre-release, at least this time around, it's there!

https://github.com/linux-msm/cdba/releases/tag/v1.0
